services:

  servicedesk-caddy:
    image: caddy:2.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - servicedesk-api-gateway-prod
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - servicedesk-network
      
  servicedesk-api-gateway-prod:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.prod
    image: servicedesk-api-gateway-prod
    working_dir: /app
    expose: [8000]
    # env_file:
    #   - .env
    environment:
      SERVER_PORT: "8000"
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      USER_BASE_URL: "servicedesk-user-service-prod:8081"
      TICKET_BASE_URL: "servicedesk-ticket-service-prod:8082"
    networks:
      - servicedesk-network
      
  servicedesk-user-service-prod:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.prod
    image: servicedesk-user-service-prod
    working_dir: /app
    expose: [8081]
    environment:
      SERVER_PORT: "8081"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    networks:
      - servicedesk-network

  servicedesk-ticket-service-prod:
    build:
      context: ./backend/ticket-service
      dockerfile: Dockerfile.prod
    image: servicedesk-ticket-service-prod
    working_dir: /app
    expose: [8082]
    environment:
      SERVER_PORT: "8082"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    networks:
      - servicedesk-network
      
networks:
  servicedesk-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
