services:

  helpdesk-caddy:
    image: caddy:2.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - helpdesk-api-gateway-prod
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - helpdesk-network
      
  helpdesk-api-gateway-prod:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.prod
    image: helpdesk-api-gateway-prod
    working_dir: /app
    expose: [8000]
    # env_file:
    #   - .env
    environment:
      SERVER_PORT: "8000"
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      USER_BASE_URL: "helpdesk-user-service-prod:8081"
      TICKET_BASE_URL: "helpdesk-ticket-service-prod:8082"
    networks:
      - helpdesk-network
      
  helpdesk-user-service-prod:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.prod
    image: helpdesk-user-service-prod
    working_dir: /app
    expose: [8081]
    environment:
      SERVER_PORT: "8081"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_DATA_MONGODB_DB_NAME: ${SPRING_DATA_MONGODB_DB_NAME}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    networks:
      - helpdesk-network

  helpdesk-ticket-service-prod:
    build:
      context: ./backend/ticket-service
      dockerfile: Dockerfile.prod
    image: helpdesk-ticket-service-prod
    working_dir: /app
    expose: [8082]
    environment:
      SERVER_PORT: "8082"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_DATA_MONGODB_DB_NAME: ${SPRING_DATA_MONGODB_DB_NAME}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    networks:
      - helpdesk-network
      
networks:
  helpdesk-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
