services:

  helpdesk-caddy:
    image: caddy:2.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - helpdesk-api-gateway-dev
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - helpdesk-network

  helpdesk-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: helpdesk-frontend-dev
    ports: [5173:5173]
    environment:
      VITE_API_BASE_URL: ${API_SERVER_URL_LOCAL}
      VITE_CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      VITE_CLOUDINARY_UPLOAD_PRESET: ${CLOUDINARY_UPLOAD_PRESET}
      VITE_CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
    networks:
      - helpdesk-network
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
      
  helpdesk-api-gateway-dev:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile.dev
    image: helpdesk-api-gateway-dev
    working_dir: /app/api-gateway
    expose: [8000]
    command: ["./mvnw", "clean", "spring-boot:run"]
    environment:
      SERVER_PORT: "8000"
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      USER_BASE_URL: "helpdesk-user-service-dev:8081"
      TICKET_BASE_URL: "helpdesk-ticket-service-dev:8082"
      JWT_KEY: ${JWT_KEY}
    volumes:
      - ./backend:/app
      - ${HOME}/.m2:/root/.m2
    networks:
      - helpdesk-network
      
  helpdesk-user-service-dev:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile.dev
    image: helpdesk-user-service-dev
    working_dir: /app/user-service
    expose: [8081]
    command: ["./mvnw", "clean", "spring-boot:run"]
    environment:
      SERVER_PORT: "8081"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_DATA_MONGODB_DB_NAME: ${SPRING_DATA_MONGODB_DB_NAME}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
      JWT_KEY: ${JWT_KEY}
    volumes:
      - ./backend:/app
      - ${HOME}/.m2:/root/.m2
    networks:
      - helpdesk-network

  helpdesk-ticket-service-dev:
    build:
      context: ./backend
      dockerfile: ticket-service/Dockerfile.dev
    image: helpdesk-ticket-service-dev
    working_dir: /app/ticket-service
    expose: [8082]
    command: ["./mvnw", "clean", "spring-boot:run"]
    environment:
      SERVER_PORT: "8082"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SPRING_DATA_MONGODB_DB_NAME: ${SPRING_DATA_MONGODB_DB_NAME}
      API_SERVER_URL: ${API_SERVER_URL_LOCAL}
      USER_BASE_URL: "helpdesk-user-service-dev:8081"
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      POLLINATIONS_API_KEY: ${POLLINATIONS_API_KEY}
    volumes:
      - ./backend:/app
      - ${HOME}/.m2:/root/.m2
    networks:
      - helpdesk-network
      
networks:
  helpdesk-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  node_modules:
